config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root to: 'members#index'
  end

  root to: 'pages#home'

  resources :members do
    resources :vaccines, only: [:show]
  end
  resources :vaccines, only:[:index]

  resources :appointments, only: [:show, :new, :create, :index]

  resources :member_vaccines, only: [:show, :edit, :update], as: :member_vaccine_show

  post '/vaccinate_member', to: "vaccines#vaccinate", as: "vaccinate"

  get 'confirmed/:id', to: 'appointments#confirmed', as: 'confirmed'

  post '/email_confirmed/:id', to: 'appointments#email_confirmed', as: 'email_confirmed'

  get '/about', to: 'application#about', as: 'about'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex">
  <div class="col-xs-6 footer-links pl-3">
    <!-- <a href="#"><i class="fab fa-github"></i></a> -->
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
   <!--  <a href="#"><i class="fab fa-linkedin"></i></a> -->
  </div>
  <div class="footer-copyright">
    Made by
    <span>
      <img class="avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/thierryfro" />
      <img class="avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/nannazinha" />
      <img class="avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/mimipacheco" />
      <img class="avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/joaopthompson" />
    </span> at Jenner <i class="far fa-copyright"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <!-- LOGO -->
    <div class="">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.png", id: "logo" %>
      <% end %>
    </div>
    <!-- LINKS MENU - LOGGED IN-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", members_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Quem Somos", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
<!-- LINKS MENU - LOGGED OUT-->
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <!-- LOGO -->
    <div class="">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.png", id: "logo" %>
      <% end %>
    </div>
    <!-- LINKS MENU - LOGGED IN-->
    <div id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
         <li class="nav-item ">
          <%= link_to "Login", new_user_session_path %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<% if user_signed_in? %>


<!-- SIDEBAR -->
<nav id="sidebar" class="active">
  <!-- TOGGLE BUTTON -->
  <div class="sidebar-header text-center ">
    <div class="toggle-btn">
      <button type="button" id="sidebarCollapse" class="btn toggle-btn">
        <i class="fas fa-arrows-alt-h"></i>
      </button>
    </div>
  </div>


  <!-- TOGGLE BUTTON -->
  <div class="navbar-header">

    <!-- IMAGE MEMBER - TITULAR -->
    <div class="container-fluid">
      <% if @master %>
      <%= cl_image_tag @master.photo, class: "rounded-circle img-fluid w-75 self-align mx-auto d-block" %>
      <div  class="text-center py-2">
        <h3><span><b> <%= @master.first_name %></b></span></h3>
      </div>
      <% else %>
      <%= image_tag "default.jpg", class: "rounded-circle img-fluid w-75"  %>
      <% end %>
    </div>

    <!-- MENU -->
    <ul class="list-unstyled components">
      <li>
        <a href="/members">
          <i class="fas fa-home"></i>
          <span>Home</span>
        </a>
      </li>
      <li>
        <a href="/members/new">
          <i class="fas fa-user-plus"></i>
          <span>Novo Membro</span>
        </a>
      </li>
      <li>
        <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">
          <i class="far fa-id-card"></i>
          <span>Cartões de Vacinas</span>
        </a>
        <!-- MEMBERS VACCINES LINKS -->
        <ul class="collapse list-unstyled" id="pageSubmenu">
          <% current_user.members.each do |member| %>
          <li><%= link_to member.first_name, member_path(member.id) %></li>
          <% end %>
        </ul>
      </li>
      <li>
        <a href="/appointments">
          <i class="far fa-calendar-alt text-truncate"></i>
          <span>Meus agendamentos</span>
        </a>
      </li>
      <li>
        <a href="/vaccines">
          <i class="fas fa-syringe"></i>
          <span>Vacinas</span>
        </a>
      </li>
      <li >
        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">
          <i class="fas fa-cog"></i>
          <span>Configurações</span>
        </a>
        <ul class="collapse list-unstyled" id="homeSubmenu">
          <li><%= link_to "Sobre", about_path %></li>
        </ul>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fas fa-sign-out-alt"></i>
        <span>Sair</span>
        <% end %>
      </li>
    </ul>
  </nav>
  <% end %>