config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root to: 'members#index'
  end

  root to: 'pages#home'

  resources :members do
    resources :vaccines, only: [:show]
  end
  resources :vaccines, only:[:index]

  resources :appointments, only: [:show, :new, :create, :index]

  resources :member_vaccines, only: [:show, :edit, :update], as: :member_vaccine_show

  post '/vaccinate_member', to: "vaccines#vaccinate", as: "vaccinate"

  get 'confirmed/:id', to: 'appointments#confirmed', as: 'confirmed'

  post '/email_confirmed/:id', to: 'appointments#email_confirmed', as: 'email_confirmed'

  get '/about', to: 'application#about', as: 'about'

end

app/models/vaccine.rb
class Vaccine < ApplicationRecord
  has_many :member_vaccines
  has_many :members, through: :member_vaccines
  has_many :laboratory_vaccines
  has_many :laboratories, through: :laboratory_vaccines
end

app/controllers/vaccines_controller.rb
class VaccinesController < ApplicationController
  before_action :set_vaccine, only: [:show, :vaccinate]
  before_action :set_member, only: [:show, :vaccinate]

  def index
    @vaccines = Vaccine.all
  end

  def show
    # .where = vaccine
    @laboratories = Laboratory.geocoded #returns labs with coordinates
    @markers = @laboratories.map do |laboratory|
      if laboratory.category == "private"
        {
          lat: laboratory.latitude,
          lng: laboratory.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { laboratory: laboratory, laboratory_vaccine: LaboratoryVaccine.find_by(laboratory: laboratory, vaccine: @vaccine) }),
          image_url: helpers.asset_url('icon_blue.png')
        }
      else
        {
          lat: laboratory.latitude,
          lng: laboratory.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { laboratory: laboratory }),
          image_url: helpers.asset_url('icon_red.png')
        }
      end
    end
  end

  def vaccinate
    member_vaccine = MemberVaccine.find_by(vaccine: @vaccine, member: @member)
    member_vaccine.vaccinated = !member_vaccine.vaccinated
    appointment = Appointment.find_by(vaccine: @vaccine, member: @member)
    member_vaccine.vaccine_date = appointment.date
    member_vaccine.save!
    if MemberVaccine.find_by(vaccine: appointment.vaccine, member: appointment.member).vaccinated == true
      mail = UserMailer.with(member: @member, vaccine: @vaccine, appointment: appointment, user: current_user).create_confirmation_vaccinate
      mail.deliver_now
    end
    redirect_to @member
  end

  private

  def set_vaccine
    @vaccine = Vaccine.find(params[:id])
  end

  def set_member
    @member = Member.find(params[:member_id])
  end
end

app/views/vaccines/_info_window.html.erb
<h6><b><%= laboratory.name %></b></h6>
<%= laboratory.address %>
<br>
<%= laboratory.phone %>
<br>
<%= laboratory.opening_time %>h às <%= laboratory.closing_time %>h
<br>
<%= laboratory.website %>
<br>
<br>


  <% if laboratory.category == "private" %>

    <h6><b><%= humanized_money_with_symbol((laboratory_vaccine.price)/100) %></b></h6>

    <%= link_to "Agendar", new_appointment_path(vaccine_id: @vaccine.id, laboratory_id: laboratory.id, member_id: @member.id), class: "btn btn-box btn-primary" %>
  <% end %>

app/views/vaccines/index.html.erb
<div class="container mb-3">
  <div class="col-12 col-lg-12 custom-margin-top">
    <div class="vaccine-list-header">
      <h1>LISTA DE VACINAS</h1>
      <h4 class="text-center">Clique na vacina para obter mais informações</h4>
    </div>

    <div class="row">
      <div class="col-12 col-lg-6 offset-lg-3">
        <% index = 0 %>
        <% vaccine_index.each do |vaccine| %>
          <li class="list-unstyled">
            <button class="vaccine-list-btn btn-full btn-primary" href="#Submenu-<%= index %>" data-toggle="collapse" aria-expanded="false">
              <i class="fas fa-syringe"></i>
                <span><%=vaccine[0] %></span>
            </button>
            <ul class="collapse list-unstyled mt-2" id="Submenu-<%= index %>">
              <li><%= vaccine[1] %></li>
            </ul>
          </li>
          <% index += 1 %>
        <% end %>

        <p style="margin-top: 10px"><%= link_to 'Voltar à página principal', members_path %></p>
      </div>
    </div>
  </div>
</div>

app/views/vaccines/show.html.erb
<div class="container">
  <div class="col-12 col-lg-8 offset-lg-2 custom-margin-top">
    <h1>ESCOLHA A CLÍNICA</h1>

    <div class="card">
      <div class="card-body">
        <% if @member.photo.url %>
          <%= cl_image_tag @member.photo, class: "float-left rounded-circle w-25 mr-4" %>
        <% else %>
          <%= image_tag "default.jpg", class: "float-left rounded-circle w-25 mr-4" %>
        <% end %>
        <div class="message">
          <h5 class="card-title"><%= @member.first_name.upcase %> <%= @member.last_name.upcase %></h5>
          <h6 class="card-subtitle mb-3 text-muted"> <%= @member.birth_date.strftime("%d/%m/%Y") %> | <%= @member.gender %></h6>
          <p class="card-text"><%= @member.category %></p>
        </div>
      </div>
    </div>


    <li class="list-unstyled mb-2">
      <button class="vaccine-list-btn btn-full btn-primary" href="#Submenu-<%= @vaccine.id %>" data-toggle="collapse" aria-expanded="false">
        <i class="fas fa-syringe"></i>
          <span><%= @vaccine.name %></span>
      </button>
      <ul class="collapse list-unstyled mt-2" id="Submenu-<%= @vaccine.id %>">
        <li><p><%= @vaccine.description %></p></li>
      </ul>
    </li>

    <div
      id="map"
      style="width: 100%;
      height: 500px;
      border-radius: 10px"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>

    <div class="map-key">
      <div><%= image_tag "icon_red.png" %></div><p>REDE PÚBLICA</p>
      <div><%= image_tag "icon_blue.png" %></div><p>REDE PRIVADA</p>
    </div>
  </div>
</div>