config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root to: 'members#index'
  end

  root to: 'pages#home'

  resources :members do
    resources :vaccines, only: [:show]
  end
  resources :vaccines, only:[:index]

  resources :appointments, only: [:show, :new, :create, :index]

  resources :member_vaccines, only: [:show, :edit, :update], as: :member_vaccine_show

  post '/vaccinate_member', to: "vaccines#vaccinate", as: "vaccinate"

  get 'confirmed/:id', to: 'appointments#confirmed', as: 'confirmed'

  post '/email_confirmed/:id', to: 'appointments#email_confirmed', as: 'email_confirmed'

  get '/about', to: 'application#about', as: 'about'

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :laboratory
  belongs_to :vaccine
  belongs_to :member
  # validates :date, presence: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_laboratory, only: [:new]
  before_action :set_member, only: [:new]
  before_action :set_vaccine, only: [:new]

  def index
    @appointments = Appointment.joins(:member).where(members: {user: current_user}).order("created_at DESC")
  end

  def show
    @appointment = Appointment.find(params[:id])
    qrcode = RQRCode::QRCode.new("appointment-#{@appointment.id}")

    # NOTE: showing with default options specified explicitly
    @svg = qrcode.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 6
    )
  end

  def new
    @appointment = Appointment.new
    respond_to do |format|
      format.html
      format.js
    end
    @price = LaboratoryVaccine.find_by(laboratory: @laboratory, vaccine: @vaccine).price
  end

  def confirmed
    @appointment = Appointment.find(params[:id])
    @laboratory = @appointment.laboratory
    @vaccine = @appointment.vaccine
    @vaccine_laboratory = LaboratoryVaccine.find_by(laboratory: @laboratory, vaccine: @vaccine)
  end

  def email_confirmed
    @appointment = Appointment.find(params[:id])
    mail = UserMailer.with(appointment: @appointment, user: current_user).create_confirmation_appointment
    mail.deliver_now
    redirect_to @appointment
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @price = LaboratoryVaccine.where(laboratory: @appointment.laboratory, vaccine: @appointment.vaccine).last.price
    @appointment.price = @price

    if @appointment.save!
      # raise
      member_vaccine = MemberVaccine.find_by(vaccine: @appointment.vaccine, member: @appointment.member)
      member_vaccine.vaccinated = false
      member_vaccine.save

      redirect_to confirmed_path(@appointment)

    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  private

  def set_laboratory
    @laboratory = Laboratory.find(params[:laboratory_id])
  end

  def set_member
    @member = Member.find(params[:member_id])
  end

  def set_vaccine
    @vaccine = Vaccine.find(params[:vaccine_id])
  end

  def appointment_params
    params.require(:appointment).permit(:date, :status, :price, :laboratory_id, :member_id, :vaccine_id)
  end
end

app/views/appointments/confirmed.html.erb
<div class="container">
  <div class="col-12 col-lg-6 offset-lg-3 custom-margin-top">

    <h1>PAGAMENTO</h1>
    <div class="appointment-new-card">
      <div>
        <% if @laboratory.category == "public" %>
          <%= image_tag "icon_red.png" %>
        <% else %>
          <%= image_tag "icon_blue.png" %>
        <% end %>
      </div>
      <div>
        <h4><strong><%= @laboratory.name.upcase %></strong></h4>
        <p>Endereço: <%= @laboratory.address %></p>
        <p>Tel: <%= @laboratory.phone %></p>
        <p>Horário: <%= @laboratory.opening_time %>h às <%= @laboratory.closing_time %>h</p>
        <p><%= link_to @laboratory.website, @laboratory.website %></p>
        <br>
        <h4><strong><%= @vaccine.name.upcase %></strong></h4>
        <h4>R$<%= (@vaccine_laboratory.price)/100 %></h4>
      </div>
    </div>
    <h4 id="date-modal"></h4>
    <%= form_tag email_confirmed_path(@appointment), method: :post do %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <script type="text/javascript"
        src="https://assets.pagar.me/checkout/checkout.js"
        data-encryption-key="<%= ENV['PAGARME_ENCRYPTION_KEY'] %>"
        data-ui-color="#808080"
        data-header-text="<%= "#{@laboratory.name} <br/> #{@vaccine.name} - R$ #{LaboratoryVaccine.find_by(vaccine: @vaccine, laboratory: @laboratory).price / 100}" %>"
        data-customer-email="<%= current_user.email %>"
        data-create-token="false"
        data-button-class="btn btn-primary"
        data-amount="<%= @vaccine_laboratory.price_cents / 100 %>">
      </script>
    <% end %>
  </div>
</div>

app/views/appointments/index.html.erb
<div class="container container-table">
  <div class="col-12 col-lg-12 custom-margin-top">
    <div class="appointments-new-card">
      <h1><strong>MEUS AGENDAMENTOS</strong></h1>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col" class="table-title">ID</th>
                <th scope="col" class="table-title"></th>
                <th scope="col" class="table-title">Membro</th>
                <th scope="col" class="table-title">Vacina</th>
                <th scope="col" class="table-title">Local</th>
                <th scope="col" class="table-title">Data/Horário</th>
                <th scope="col" class="table-title">Valor</th>
                <th scope="col" class="table-title">Confirmação</th>
                <th scope="col" class="table-title">Status</th>
              <br>
              </tr>
            </thead>
            <tbody>
              <% @appointments.each do |appointment| %>
                <tr>
                  <th scope="row"><%= appointment.id %></th>
                  <td><%= cl_image_tag appointment.member.photo, width: 38, crop: :fill, class: "confirmed-photo" %></td>
                  <td><%= appointment.member.first_name %> <%= appointment.member.last_name %></td>
                  <td><%= appointment.vaccine.name %></td>
                  <td><%= appointment.laboratory.name %></td>
                  <td><%= appointment.date.strftime("%d/%m/%Y / %H:%M") %></td>
                  <td>R$<%= (appointment.price)/100 %></td>
                  <td><%= link_to "Confirmação", appointment_path(appointment), class: 'btn btn-primary' %></td>
                  <td>
                    <% if MemberVaccine.find_by(vaccine: appointment.vaccine, member: appointment.member).vaccinated == false %>
                      <%= form_tag vaccinate_path do %>
                        <%= hidden_field_tag :id, appointment.vaccine.id %>
                        <%= hidden_field_tag :member_id, appointment.member.id %>
                        <%= submit_tag "Não realizada", class: 'btn btn-danger' %>
                      <% end %>
                    <% else %>
                      <%= form_tag vaccinate_path do %>
                        <%= hidden_field_tag :id, appointment.vaccine.id %>
                        <%= hidden_field_tag :member_id, appointment.member.id %>
                        <%= submit_tag "Realizada", class: 'btn btn-success' %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <br>
      <p><%= link_to "Voltar à página principal", members_path %></p>
    </div>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="container-table">
  <div class="col-12 col-lg-8 offset-lg-2 custom-margin-top">

    <h1>ESCOLHA UMA DATA E HORÁRIO</h1>
    <div class="appointment-new-card">
      <div>
        <% if @laboratory.category == "public" %>
          <%= image_tag "icon_red.png" %>
        <% else %>
          <%= image_tag "icon_blue.png" %>
        <% end %>
      </div>
      <div>
        <h4><strong><%= @laboratory.name.upcase %></strong></h4>
        <p>Endereço: <%= @laboratory.address %></p>
        <p>Tel: <%= @laboratory.phone %></p>
        <p>Horário: <%= @laboratory.opening_time %>h às <%= @laboratory.closing_time %>h</p>
        <p><%= link_to @laboratory.website, @laboratory.website %></p>
        <br>
        <h4><strong><%= @vaccine.name.upcase %></strong></h4>
        <h4>R$<%= @price/100 %></h4>
      </div>
    </div>

    <div class="col-12">
      <%= simple_form_for @appointment, method: :post do |f| %>
        <%= f.input :vaccine_id, as: :hidden, input_html: { value: @vaccine.id } %>
        <%= f.input :member_id, as: :hidden, input_html: { value: @member.id } %>
        <%= f.input :laboratory_id, as: :hidden, input_html: { value: @laboratory.id, data: {opening_time: "#{@laboratory.opening_time}:00", closing_time: "#{@laboratory.closing_time}:00" }} %>
        <%= f.input :date, label: "Escolha uma data:", as: :string, required: true, input_html: {class: "datepicker"} %>
        <a id="date-button" class="btn disabled"><%= f.submit 'Agendar' %></a>
      <% end%>
    </div>

  </div>
</div>

app/views/appointments/show.html.erb
<div class="container container-table">
  <div class="col-12 custom-margin-top"></div>

    <h1>SEU AGENDAMENTO FOI CONFIRMADO!</h1>
    <div class="appointment-new-card justify-content-center">
      <div>
        <h6>O pedido número <b><%= @appointment.id %></b> foi aprovado! Um email de confirmação foi enviado.</h6>
      </div>
    </div>
    <br>
    <div class="text-center">
      <%= raw(@svg) %>
    </div>
    <h1>DETALHES DO PEDIDO</h1>

    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col" class="table-title">ID</th>
            <th scope="col" class="table-title">Membro</th>
            <th scope="col" class="table-title">Vacina</th>
            <th scope="col" class="table-title">Local</th>
            <th scope="col" class="table-title">Data/Horário</th>
            <th scope="col" class="table-title">Valor</th>
            <br>
          </tr>
        </thead>
        <tbody>
            <%# @current_user.appointments.each do |appointment| %>
          <tr>
            <td><%= @appointment.id %></td>
            <td><%= cl_image_tag @appointment.member.photo, width: 38, crop: :fill, class: "confirmed-photo" %>
                <%= @appointment.member.first_name %> <%= @appointment.member.last_name %></td>
            <td><%= @appointment.vaccine.name %></td>
            <td><%= @appointment.laboratory.name %></td>
            <td><%= @appointment.date.strftime("%d/%m/%Y / %H:%M") %></td>
            <td>R$<%= (@appointment.price)/100 %></td>
          </tr>
            <%# end %>
        </tbody>
        </table>
    </div>
    <br>
    <p><%= link_to "Voltar à página principal", members_path %> | <%= link_to "Voltar à página do familiar", member_path(@appointment.member_id) %> | <%= link_to "Ver todos os agendamentos", appointments_path(@appointment.member_id) %></p>
  </div>
</div>