config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root to: 'members#index'
  end

  root to: 'pages#home'

  resources :members do
    resources :vaccines, only: [:show]
  end
  resources :vaccines, only:[:index]

  resources :appointments, only: [:show, :new, :create, :index]

  resources :member_vaccines, only: [:show, :edit, :update], as: :member_vaccine_show

  post '/vaccinate_member', to: "vaccines#vaccinate", as: "vaccinate"

  get 'confirmed/:id', to: 'appointments#confirmed', as: 'confirmed'

  post '/email_confirmed/:id', to: 'appointments#email_confirmed', as: 'email_confirmed'

  get '/about', to: 'application#about', as: 'about'

end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  has_many :member_vaccines, dependent: :destroy
  has_many :vaccines, through: :member_vaccines
  has_many :appointments, dependent: :destroy
  accepts_nested_attributes_for :member_vaccines, allow_destroy: true
  mount_uploader :photo, PhotoUploader
  has_many :orders
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birth_date, presence: true
  validates :category, presence: true
  validates :gender, presence: true
end

app/controllers/members_controller.rb
require "time"

class MembersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_member, only: %i( show edit update destroy show_alert)
  skip_before_action :has_members, only: %i(new create)

  def index
    @members = Member.where(user: current_user)
  end

  def show
  end

  def new
    @master = current_user.members.find_by(category: "Titular")
    @member = Member.new
    @member.member_vaccines.build
    @vaccines = []
  end

  def create
    @member = Member.new(member_params)
    @member.user = current_user
    if @member.save
      Vaccine.all.each do |vaccine|
        MemberVaccine.create(member: @member, vaccine: vaccine)
      end
      mail = UserMailer.with(member: @member, user: current_user).create_confirmation_member
      mail.deliver_now
      redirect_to member_path(@member)
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  def edit
  end

  def update
    @member.update(member_params)
    # mail = UserMailer.with(member: @member, user: current_user).update_confirmation_member
    # mail.deliver_now
    redirect_to member_path(@member)
  end

  def destroy
    @member.destroy
    mail = UserMailer.with(member: @member, user: current_user).destroy_confirmation_member
    mail.deliver_now
    redirect_to members_path
  end

  private

  def set_member
    @member = Member.find(params[:id])
  end

  def member_params
    params.require(:member).permit( :first_name,
                                    :last_name,
                                    :birth_date,
                                    :gender,
                                    :category,
                                    :photo,
                                    member_vaccines_attributes: [ :id,
                                                                  :vaccine_id,
                                                                  :member_id,
                                                                  :vaccine_date,
                                                                  :vaccinated])
  end
end

app/views/members/_form.html.erb
<div class="container">
  <div class="col-12 col-lg-8 offset-lg-2 custom-margin-top">
    <div class="form-member">

      <h1>ADICIONAR FAMILIAR</h1>
      <%= simple_form_for(@member) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="row">
          <div class="col-lg-6">
            <%= f.input :first_name, label: 'Nome' %>
          </div>
          <div class="col-lg-6">
            <%= f.input :last_name, label: 'Sobrenome' %>
          </div>
        </div>

        <%= f.input :birth_date, order: [:day, :month, :year], prompt: " ", end_year: Date.today.year - 100, start_year: Date.today.year, label: 'Data de nascimento'%>

        <div class="row">
          <div class="col-6">
            <%= f.input :gender, as: :radio_buttons, collection: ['Feminino', 'Masculino'], label: 'Sexo' %>
          </div>
          <div class="col-6">
            <%= f.input :category, as: :radio_buttons, collection: ['Titular', 'Dependente'], label: 'Conta' %>
          </div>
        </div>

        <%= f.input :user_id, as: :hidden %>
        <%= f.input :photo, label: 'Foto' %>
        <%= f.input :photo_cache, as: :hidden %>

    </div>
          <%= f.button :submit, "Adicionar", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/members/edit.html.erb
<div class="container">
  <div class="col-12 col-lg-8 offset-lg-2 custom-margin-top">
    <div class="form-edit">
      <h1>EDITAR DADOS PESSOAIS DO FAMILIAR</h1>
      <%= simple_form_for(@member) do |f| %>

        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="row">
          <div class="col-lg-6">
            <%= f.input :first_name, label: 'Nome' %>
          </div>
          <div class="col-lg-6">
            <%= f.input :last_name, label: 'Sobrenome' %>
          </div>
        </div>

        <%= f.input :birth_date, order: [:day, :month, :year], end_year: Date.today.year - 100, start_year: Date.today.year, label: 'Data de Nascimento' %>

        <div class="row">
          <div class="col-6">
            <%= f.input :gender, as: :radio_buttons, collection: ['Feminino', 'Masculino'], label: 'Sexo' %>
          </div>
          <div class="col-6">
            <%= f.input :category, as: :radio_buttons, collection: ['Titular', 'Dependente'], label: 'Conta' %>
          </div>
        </div>

        <%= f.input :photo, label: 'Foto' %>
        <%= f.input :photo_cache, as: :hidden %>

        <%= f.input :user_id, as: :hidden %>

        <%= f.button :submit, "Editar", class: "btn btn-primary" %>

      <% end %>

    </div>
    <div class="mt-5 mb-3">
      <%= link_to 'Voltar ao perfil', @member %> | <%= link_to 'Voltar à página principal', members_path %>
    </div>
  </div>
</div>

app/views/members/index.html.erb
<div class="container vaccine-container">
  <div class="row">
    <div class="container">
      <div class="row">
        <% @members.each do |member| %>
          <% if vaccine_expired(member).size != 0 %>
            <div class="col-12 col-sm-6 text-center py-2 flash-pos custom-margin-top">
              <div class="flash flash-danger alert-dismissible fade show animated slow bounce delay-5s alert-x" role="alert">
                <span><strong><%= link_to "#{member.first_name}: Está com alguma vacina atrasada! 😱", member_path(member), class: "alert-link" %></strong></span>
                <a data-dismiss="alert" aria-label="Close">
                </a>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <br>

  <div class="row d-flex justify-content-between">
    <div class="col-12 col-lg-4">
      <div class="card mb-2">
        <div class="card-body card-index">
          <h5 class="card-title text-center">CADASTRE SUA FAMÍLIA</h5>
          <p class="card-text">Cadastre-se no Jenner como titular de sua conta e seus familiares como dependentes em <b>Adicionar Membro</b></p>
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <div class="card mb-2">
        <div class="card-body card-index">
          <h5 class="card-title text-center">VACINAS ATUALIZADAS</h5>
          <p class="card-text">Preencha os dados de vacinas passadas no perfil do familiar e mantenha o histórico atualizado. Clique na opção <b>Editar Vacinas Tomadas</b> no perfil do familiar</p>
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <div class="card mb-2">
        <div class="card-body card-index">
          <h5 class="card-title text-center">AGENDE NOVAS VACINAS</h5>
          <p class="card-text">Agende e pague por vacinas pendentes em clínicas particulares com conveniência. Clique no ícone da <b>Vacina Pendente</b> no perfil do familiar</p>
        </div>
      </div>
    </div>
  </div>

  <h1>MEUS FAMILIARES</h1>

  <div class="member-cont my-4">
    <% @members.each do |member| %>
    <%= link_to member_path(member) do %>

    <div class="card-member m-3">
      <div class= 'card-content' >
        <% if vaccine_expired(member).size != 0 %>
        <div class="notif">
          <span class="align-middle"><h3><%= vaccine_expired(member).size %></h3></span>
        </div>
        <% end %>


        <% if member.photo.url %>
        <%= cl_image_tag member.photo, class: "rounded-circle img-fluid" %>
        <% else %>
        <%= image_tag "default.jpg", class: "rounded-circle img-fluid"  %>
        <% end %>
        <h3 class="mt-3"> <b> <%= member.first_name %></b> </h3>

      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/members/new.html.erb
  <%= render 'form', member: @member %>

app/views/members/show.html.erb
<div class="container">
  <div class="col-12 col-lg-8 offset-lg-2 custom-margin-top">
    <h1>CARTÃO DE VACINAS</h1>

    <div class="card">
      <div class="card-body">
        <% if @member.photo.url %>
        <%= cl_image_tag @member.photo, class: "float-left rounded-circle w-25 mr-4" %>
        <% else %>
        <%= image_tag "default.jpg", class: "float-left rounded-circle w-25 mr-4" %>
        <% end %>
        <div class="message">
          <h5 class="card-title"><%= @member.first_name.upcase %> <%= @member.last_name.upcase %></h5>
          <h6 class="card-subtitle mb-3 text-muted"> <%= @member.birth_date.strftime("%d/%m/%Y") %> | <%= @member.gender %></h6>
          <p class="card-text mb-4"><%= @member.category %></p>
        </div>
        <div class="actions">
          <a href="#" class="card-link"><%= link_to "Editar dados pessoais", edit_member_path(@member) %> | </a>
          <a href="#" class="card-link"><%= link_to "Editar vacinas tomadas", edit_member_vaccine_show_path(@member) %> | </a>
          <a href="#" class="card-link"><%= link_to "Deletar", member_path(@member), method: :delete, data: { confirm: "Tem certeza de quer deletar este dependente?" } %></a>
        </div>
      </div>
    </div>

    <br>

    <% if vaccine_expired(@member).size != 0 %>
      <h1>VACINAS PENDENTES</h1>
    <% end %>

    <div class="row">
      <% vaccine_expired(@member).each do |mv| %>
      <div class="col-6 col-md-4 col-lg-3">
        <div class="vaccines-expired">
          <%= link_to image_tag("#{mv.image}"), member_vaccine_path(@member, mv) %>
          <%#= mv.vaccine_date %>
        </div>
      </div>
      <% end %>
    </div>

    <% if vaccine_next(@member).size != 0 %>
      <h1>VACINAS PRÓXIMAS</h1>
    <% end %>

    <div class="row">
      <% vaccine_next(@member).each do |mv| %>
      <div class="col-6 col-md-4 col-lg-3">
        <div class="vaccines-next">
          <%= link_to image_tag("#{mv.image}"), member_vaccine_path(@member, mv) %> <%#= mv.vaccine_date %>
        </div>
      </div>
      <% end %>
    </div>

    <% if vaccine_taken(@member).size != 0 %>
      <h1>VACINAS TOMADAS</h1>
    <% end %>

    <div class="row">
      <% vaccine_taken(@member).each do |mv| %>
      <div class="col-6 col-md-4 col-lg-3">
        <div class="vaccines-taken <%= Appointment.find_by(member: @member, vaccine: mv).nil? ? 'date-vaccine' : '' %>">
          <% if Appointment.find_by(member: @member, vaccine: mv.vaccine).nil? %>
          <%= image_tag("#{mv.vaccine.image}") %>
          <p><b><%= mv.vaccine_date.strftime('%d/%m/%Y') %></b></p>
          <% else %>
          <%= link_to image_tag("#{mv.vaccine.image}"), member_vaccine_show_path(Appointment.find_by(member: @member, vaccine: mv.vaccine), format: :pdf), target: :_blank %> <%#= mv.vaccine_date %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>

    <p style="margin-top: 5px"> <%= link_to "Editar", edit_member_path(@member) %> | <%= link_to "Deletar", member_path(@member), method: :delete, data: { confirm: "Tem certeza de quer deletar este dependente?" } %> | <%= link_to 'Voltar à página principal', members_path %></p>
  </div>
</div>